// Country name → { iso3, currency } lookup (shared across components)
export const COUNTRY_DATA: Record<string, { iso: string; currency: string }> = {
  "afghánistán": { iso: "AFG", currency: "AFN" },
  "albánie": { iso: "ALB", currency: "ALL" },
  "alžírsko": { iso: "DZA", currency: "DZD" },
  "andorra": { iso: "AND", currency: "EUR" },
  "angola": { iso: "AGO", currency: "AOA" },
  "argentina": { iso: "ARG", currency: "ARS" },
  "arménie": { iso: "ARM", currency: "AMD" },
  "austrálie": { iso: "AUS", currency: "AUD" },
  "ázerbájdžán": { iso: "AZE", currency: "AZN" },
  "bahamy": { iso: "BHS", currency: "BSD" },
  "bahrajn": { iso: "BHR", currency: "BHD" },
  "bangladéš": { iso: "BGD", currency: "BDT" },
  "barbados": { iso: "BRB", currency: "BBD" },
  "belgie": { iso: "BEL", currency: "EUR" },
  "belize": { iso: "BLZ", currency: "BZD" },
  "bělorusko": { iso: "BLR", currency: "BYN" },
  "bolívie": { iso: "BOL", currency: "BOB" },
  "bosna a hercegovina": { iso: "BIH", currency: "BAM" },
  "botswana": { iso: "BWA", currency: "BWP" },
  "brazílie": { iso: "BRA", currency: "BRL" },
  "brunej": { iso: "BRN", currency: "BND" },
  "bulharsko": { iso: "BGR", currency: "BGN" },
  "burkina faso": { iso: "BFA", currency: "XOF" },
  "burundi": { iso: "BDI", currency: "BIF" },
  "čad": { iso: "TCD", currency: "XAF" },
  "česko": { iso: "CZE", currency: "CZK" },
  "česká republika": { iso: "CZE", currency: "CZK" },
  "čína": { iso: "CHN", currency: "CNY" },
  "dánsko": { iso: "DNK", currency: "DKK" },
  "dominikánská republika": { iso: "DOM", currency: "DOP" },
  "egypt": { iso: "EGY", currency: "EGP" },
  "ekvádor": { iso: "ECU", currency: "USD" },
  "eritrea": { iso: "ERI", currency: "ERN" },
  "estonsko": { iso: "EST", currency: "EUR" },
  "etiopie": { iso: "ETH", currency: "ETB" },
  "filipíny": { iso: "PHL", currency: "PHP" },
  "finsko": { iso: "FIN", currency: "EUR" },
  "francie": { iso: "FRA", currency: "EUR" },
  "gambie": { iso: "GMB", currency: "GMD" },
  "ghana": { iso: "GHA", currency: "GHS" },
  "gruzie": { iso: "GEO", currency: "GEL" },
  "guatemala": { iso: "GTM", currency: "GTQ" },
  "honduras": { iso: "HND", currency: "HNL" },
  "chile": { iso: "CHL", currency: "CLP" },
  "chorvatsko": { iso: "HRV", currency: "EUR" },
  "indie": { iso: "IND", currency: "INR" },
  "indonésie": { iso: "IDN", currency: "IDR" },
  "irák": { iso: "IRQ", currency: "IQD" },
  "írán": { iso: "IRN", currency: "IRR" },
  "irsko": { iso: "IRL", currency: "EUR" },
  "island": { iso: "ISL", currency: "ISK" },
  "itálie": { iso: "ITA", currency: "EUR" },
  "izrael": { iso: "ISR", currency: "ILS" },
  "jamajka": { iso: "JAM", currency: "JMD" },
  "japonsko": { iso: "JPN", currency: "JPY" },
  "jemen": { iso: "YEM", currency: "YER" },
  "jihoafrická republika": { iso: "ZAF", currency: "ZAR" },
  "jižní korea": { iso: "KOR", currency: "KRW" },
  "jordánsko": { iso: "JOR", currency: "JOD" },
  "kambodža": { iso: "KHM", currency: "KHR" },
  "kamerun": { iso: "CMR", currency: "XAF" },
  "kanada": { iso: "CAN", currency: "CAD" },
  "kapverdy": { iso: "CPV", currency: "CVE" },
  "katar": { iso: "QAT", currency: "QAR" },
  "kazachstán": { iso: "KAZ", currency: "KZT" },
  "keňa": { iso: "KEN", currency: "KES" },
  "kolumbie": { iso: "COL", currency: "COP" },
  "kostarika": { iso: "CRI", currency: "CRC" },
  "kuba": { iso: "CUB", currency: "CUP" },
  "kuvajt": { iso: "KWT", currency: "KWD" },
  "kypr": { iso: "CYP", currency: "EUR" },
  "kyrgyzstán": { iso: "KGZ", currency: "KGS" },
  "laos": { iso: "LAO", currency: "LAK" },
  "libanon": { iso: "LBN", currency: "LBP" },
  "libye": { iso: "LBY", currency: "LYD" },
  "lichtenštejnsko": { iso: "LIE", currency: "CHF" },
  "litva": { iso: "LTU", currency: "EUR" },
  "lotyšsko": { iso: "LVA", currency: "EUR" },
  "lucembursko": { iso: "LUX", currency: "EUR" },
  "madagaskar": { iso: "MDG", currency: "MGA" },
  "maďarsko": { iso: "HUN", currency: "HUF" },
  "malajsie": { iso: "MYS", currency: "MYR" },
  "maledivy": { iso: "MDV", currency: "MVR" },
  "malta": { iso: "MLT", currency: "EUR" },
  "maroko": { iso: "MAR", currency: "MAD" },
  "mauricius": { iso: "MUS", currency: "MUR" },
  "mauritánie": { iso: "MRT", currency: "MRU" },
  "mexiko": { iso: "MEX", currency: "MXN" },
  "moldavsko": { iso: "MDA", currency: "MDL" },
  "monako": { iso: "MCO", currency: "EUR" },
  "mongolsko": { iso: "MNG", currency: "MNT" },
  "mosambik": { iso: "MOZ", currency: "MZN" },
  "myanmar": { iso: "MMR", currency: "MMK" },
  "namibie": { iso: "NAM", currency: "NAD" },
  "německo": { iso: "DEU", currency: "EUR" },
  "nepál": { iso: "NPL", currency: "NPR" },
  "nigérie": { iso: "NGA", currency: "NGN" },
  "nikaragua": { iso: "NIC", currency: "NIO" },
  "nizozemsko": { iso: "NLD", currency: "EUR" },
  "norsko": { iso: "NOR", currency: "NOK" },
  "nový zéland": { iso: "NZL", currency: "NZD" },
  "omán": { iso: "OMN", currency: "OMR" },
  "pákistán": { iso: "PAK", currency: "PKR" },
  "panama": { iso: "PAN", currency: "PAB" },
  "paraguay": { iso: "PRY", currency: "PYG" },
  "peru": { iso: "PER", currency: "PEN" },
  "pobřeží slonoviny": { iso: "CIV", currency: "XOF" },
  "polsko": { iso: "POL", currency: "PLN" },
  "portoriko": { iso: "PRI", currency: "USD" },
  "portugalsko": { iso: "PRT", currency: "EUR" },
  "rakousko": { iso: "AUT", currency: "EUR" },
  "rumunsko": { iso: "ROU", currency: "RON" },
  "rusko": { iso: "RUS", currency: "RUB" },
  "řecko": { iso: "GRC", currency: "EUR" },
  "salvador": { iso: "SLV", currency: "USD" },
  "saúdská arábie": { iso: "SAU", currency: "SAR" },
  "senegal": { iso: "SEN", currency: "XOF" },
  "severní makedonie": { iso: "MKD", currency: "MKD" },
  "singapur": { iso: "SGP", currency: "SGD" },
  "slovensko": { iso: "SVK", currency: "EUR" },
  "slovinsko": { iso: "SVN", currency: "EUR" },
  "spojené arabské emiráty": { iso: "ARE", currency: "AED" },
  "spojené státy": { iso: "USA", currency: "USD" },
  "spojené státy americké": { iso: "USA", currency: "USD" },
  "srbsko": { iso: "SRB", currency: "RSD" },
  "srí lanka": { iso: "LKA", currency: "LKR" },
  "středoafrická republika": { iso: "CAF", currency: "XAF" },
  "súdán": { iso: "SDN", currency: "SDG" },
  "surinam": { iso: "SUR", currency: "SRD" },
  "svazijsko": { iso: "SWZ", currency: "SZL" },
  "eswatini": { iso: "SWZ", currency: "SZL" },
  "sýrie": { iso: "SYR", currency: "SYP" },
  "španělsko": { iso: "ESP", currency: "EUR" },
  "švédsko": { iso: "SWE", currency: "SEK" },
  "švýcarsko": { iso: "CHE", currency: "CHF" },
  "tádžikistán": { iso: "TJK", currency: "TJS" },
  "tanzanie": { iso: "TZA", currency: "TZS" },
  "thajsko": { iso: "THA", currency: "THB" },
  "tchaj-wan": { iso: "TWN", currency: "TWD" },
  "togo": { iso: "TGO", currency: "XOF" },
  "trinidad a tobago": { iso: "TTO", currency: "TTD" },
  "tunisko": { iso: "TUN", currency: "TND" },
  "turecko": { iso: "TUR", currency: "TRY" },
  "turkmenistán": { iso: "TKM", currency: "TMT" },
  "uganda": { iso: "UGA", currency: "UGX" },
  "ukrajina": { iso: "UKR", currency: "UAH" },
  "uruguay": { iso: "URY", currency: "UYU" },
  "uzbekistán": { iso: "UZB", currency: "UZS" },
  "venezuela": { iso: "VEN", currency: "VES" },
  "vietnam": { iso: "VNM", currency: "VND" },
  "zambie": { iso: "ZMB", currency: "ZMW" },
  "zimbabwe": { iso: "ZWE", currency: "ZWL" },
  "černá hora": { iso: "MNE", currency: "EUR" },
  "kosovo": { iso: "XKX", currency: "EUR" },
  "seychely": { iso: "SYC", currency: "SCR" },
  "fidži": { iso: "FJI", currency: "FJD" },
  "cookovy ostrovy": { iso: "COK", currency: "NZD" },
  "dominika": { iso: "DMA", currency: "XCD" },
  "antigua a barbuda": { iso: "ATG", currency: "XCD" },
};

export const lookupCountryData = (name: string) => {
  const key = name.trim().toLowerCase();
  return COUNTRY_DATA[key] || null;
};

export const searchCountries = (query: string, limit = 10) => {
  const q = query.trim().toLowerCase();
  if (q.length < 3) return [];
  return Object.entries(COUNTRY_DATA)
    .filter(([key]) => key.includes(q))
    .slice(0, limit)
    .map(([key, val]) => ({ 
      name: key.charAt(0).toUpperCase() + key.slice(1), 
      iso: val.iso, 
      currency: val.currency 
    }));
};
