project_id = "jwaskoeqryjdjrdwupoi"

[functions.send-voucher-email]
verify_jwt = true

[functions.ocr-document]
verify_jwt = true

[functions.translate-contract-to-voucher]
verify_jwt = false

[functions.parse-bulk-client-data]
verify_jwt = true

[functions.parse-bulk-supplier-data]
verify_jwt = true

[functions.translate-service-name]
verify_jwt = true

[functions.get-public-offer]
verify_jwt = false

[functions.parse-payment-email]
verify_jwt = false

[functions.confirm-payment-match]
verify_jwt = false

[functions.bank-webhook]
verify_jwt = false

[functions.sign-contract]
verify_jwt = false

[functions.send-deal-documents]
verify_jwt = true

[functions.auto-send-deal-documents]
verify_jwt = false

[functions.auto-triggered-emails]
verify_jwt = false

[functions.search-hotel-info]
verify_jwt = false

[functions.get-hotel-data]
verify_jwt = false

[functions.suggest-hotel-destination]
verify_jwt = true

[functions.submit-offer-response]
verify_jwt = false

[functions.ocr-supplier-invoice]
verify_jwt = true

[functions.get-public-accounting]
verify_jwt = false

[functions.proxy-file]
verify_jwt = false

[functions.moneta-fetch-transactions]
verify_jwt = false
