project_id = "jwaskoeqryjdjrdwupoi"

[functions.send-voucher-email]
verify_jwt = true

[functions.ocr-document]
verify_jwt = true

[functions.translate-contract-to-voucher]
verify_jwt = false

[functions.parse-bulk-client-data]
verify_jwt = true

[functions.parse-bulk-supplier-data]
verify_jwt = true

[functions.translate-service-name]
verify_jwt = true

[functions.get-public-offer]
verify_jwt = false

[functions.parse-payment-email]
verify_jwt = false

[functions.confirm-payment-match]
verify_jwt = false
