import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Save } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import yaroLogo from "@/assets/yaro-logo-wide.png";
import { toast } from "sonner";
import { ClientCombobox } from "@/components/ClientCombobox";
import { DateInput } from "@/components/ui/date-input";
import { formatDateForDB } from "@/lib/utils";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

const CreateDeal = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [startDate, setStartDate] = useState<Date | undefined>();
  const [endDate, setEndDate] = useState<Date | undefined>();
  const [notes, setNotes] = useState("");
  const [status, setStatus] = useState<"inquiry" | "quote" | "confirmed" | "completed" | "cancelled">("inquiry");
  const [leadTravelerId, setLeadTravelerId] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!leadTravelerId) {
      toast.error("Vyberte hlavního cestujícího");
      return;
    }

    setLoading(true);

    try {
      // Create deal
      const { data: deal, error: dealError } = await supabase
        .from("deals")
        .insert([{
          deal_number: '', // Will be auto-generated by trigger
          start_date: formatDateForDB(startDate),
          end_date: formatDateForDB(endDate),
          notes: notes || null,
          status: status,
        }])
        .select()
        .single();

      if (dealError) throw dealError;

      // Add lead traveler
      const { error: travelerError } = await supabase
        .from("deal_travelers")
        .insert({
          deal_id: deal.id,
          client_id: leadTravelerId,
          is_lead_traveler: true,
        });

      if (travelerError) throw travelerError;

      toast.success("Obchodní případ byl vytvořen");
      navigate(`/deals/${deal.id}`);
    } catch (error) {
      console.error("Error creating deal:", error);
      toast.error("Chyba při vytváření obchodního případu");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[var(--gradient-subtle)]">
      <div className="container max-w-4xl mx-auto py-8 px-4">
        <header className="mb-8">
          <h1 className="text-heading-1 text-foreground">
            Nový obchodní případ
          </h1>
          <p className="text-body text-muted-foreground mt-2">
            Vytvořte nový obchodní případ pro klienta
          </p>
        </header>

        <form onSubmit={handleSubmit}>
          <Card>
            <CardHeader>
              <CardTitle>Základní informace</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="status">Status *</Label>
                <Select
                  value={status}
                  onValueChange={(value: any) => setStatus(value)}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="inquiry">Poptávka</SelectItem>
                    <SelectItem value="quote">Nabídka</SelectItem>
                    <SelectItem value="confirmed">Potvrzeno</SelectItem>
                    <SelectItem value="completed">Dokončeno</SelectItem>
                    <SelectItem value="cancelled">Zrušeno</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="lead_traveler">Hlavní cestující *</Label>
                <ClientCombobox
                  value={leadTravelerId}
                  onChange={(value) => setLeadTravelerId(value)}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="start_date">Datum od</Label>
                  <DateInput
                    value={startDate}
                    onChange={setStartDate}
                    placeholder="DD.MM.RR"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="end_date">Datum do</Label>
                  <DateInput
                    value={endDate}
                    onChange={setEndDate}
                    placeholder="DD.MM.RR"
                    autoSetDate={() => startDate ? new Date(startDate.getTime() + 7 * 24 * 60 * 60 * 1000) : undefined}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="notes">Poznámky</Label>
                <Textarea
                  id="notes"
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  rows={4}
                />
              </div>
            </CardContent>
          </Card>

          <div className="mt-6 flex justify-end gap-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate("/deals")}
            >
              Zrušit
            </Button>
            <Button type="submit" disabled={loading} className="gap-2">
              <Save className="h-4 w-4" />
              {loading ? "Ukládání..." : "Vytvořit případ"}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateDeal;
