import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, Save } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useQuery } from "@tanstack/react-query";

const CreateContract = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    deal_id: "",
    terms: "",
  });

  const { data: deals } = useQuery({
    queryKey: ["deals"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("deals")
        .select(`
          id,
          deal_number,
          deal_travelers!inner(
            client:clients(first_name, last_name),
            is_lead_traveler
          )
        `)
        .eq("deal_travelers.is_lead_traveler", true)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data;
    },
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.deal_id) {
      toast.error("Vyberte obchodní případ");
      return;
    }

    setLoading(true);

    try {
      // Fetch deal details with travelers and services
      const { data: deal, error: dealError } = await supabase
        .from("deals")
        .select(`
          id,
          total_price,
          deal_travelers(client_id, is_lead_traveler),
          deal_services(service_type, service_name)
        `)
        .eq("id", formData.deal_id)
        .single();

      if (dealError) throw dealError;




      const travelers = deal.deal_travelers as any[];
      const leadTraveler = travelers?.find((t: any) => t.is_lead_traveler);

      if (!leadTraveler) {
        toast.error("Obchodní případ nemá hlavního cestujícího");
        setLoading(false);
        return;
      }

      // Use the deal's total_price, default to 0 if not set
      const totalPrice = deal.total_price !== null && deal.total_price !== undefined 
        ? Number(deal.total_price) 
        : 0;

      const { data: contract, error } = await supabase
        .from("travel_contracts")
        .insert([{
          contract_number: '', // Will be auto-generated by trigger
          deal_id: formData.deal_id,
          client_id: leadTraveler.client_id,
          total_price: totalPrice,
          status: 'draft',
          terms: formData.terms || null,
          agency_name: 'YARO s.r.o.',
          agency_address: 'Bratranců Veverkových 680, Pardubice, 530 02',
          agency_ico: '07849290',
          agency_contact: 'radek@yarotravel.cz, +420 602 102 108',
          agency_bank_account: '227993932/0600',
        }])
        .select()
        .single();

      if (error) throw error;

      // Copy services to contract_service_travelers for all travelers
      const services = deal.deal_services as any[];
      if (services && services.length > 0 && travelers && travelers.length > 0) {
        const serviceTravelers = [];
        
        for (const service of services) {
          for (const traveler of travelers) {
            serviceTravelers.push({
              contract_id: contract.id,
              client_id: traveler.client_id,
              service_type: service.service_type,
              service_name: service.service_name,
            });
          }
        }

        const { error: serviceTravelersError } = await supabase
          .from("contract_service_travelers")
          .insert(serviceTravelers);

        if (serviceTravelersError) {
          console.error("Error copying services to contract:", serviceTravelersError);
        }
      }

      // Deal payments are now automatically copied by database trigger (copy_deal_payments_on_contract_insert)

      toast.success("Cestovní smlouva byla vytvořena");
      navigate(`/contracts/${contract.id}`);
    } catch (error) {
      console.error("Error creating contract:", error);
      toast.error("Chyba při vytváření smlouvy");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-4xl mx-auto py-8 px-4">
        <div className="flex items-center gap-4 mb-8">
          <Button variant="ghost" size="icon" className="shrink-0" onClick={() => navigate("/contracts")}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex-1">
            <h1 className="text-2xl md:text-heading-1 text-foreground">
              Nová cestovní smlouva
            </h1>
            <p className="text-body text-muted-foreground mt-1">
              Vytvořte novou cestovní smlouvu podle §2521 OZ
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit}>
          <Card>
            <CardHeader>
              <CardTitle>Základní informace</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="deal">Obchodní případ *</Label>
                <Select
                  value={formData.deal_id}
                  onValueChange={(value) =>
                    setFormData({ ...formData, deal_id: value })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Vyberte obchodní případ" />
                  </SelectTrigger>
                  <SelectContent>
                    {deals?.map((deal) => {
                      const travelers = deal.deal_travelers as any[];
                      const leadTraveler = travelers?.[0];
                      const client = leadTraveler?.client;
                      const clientName = client
                        ? `${client.first_name} ${client.last_name}`
                        : '-';
                      return (
                        <SelectItem key={deal.id} value={deal.id}>
                          {deal.deal_number} - {clientName}
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle>Smluvní podmínky</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="terms">Podmínky smlouvy</Label>
                <Textarea
                  id="terms"
                  value={formData.terms}
                  onChange={(e) =>
                    setFormData({ ...formData, terms: e.target.value })
                  }
                  rows={8}
                  placeholder="Zadejte smluvní podmínky (včetně storno podmínek, pojištění a reklamačního řádu)..."
                />
              </div>
            </CardContent>
          </Card>

          <div className="mt-6 flex flex-col-reverse sm:flex-row justify-end gap-3 sm:gap-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => navigate("/contracts")}
              className="w-full sm:w-auto"
            >
              Zrušit
            </Button>
            <Button type="submit" disabled={loading} className="gap-2 w-full sm:w-auto">
              <Save className="h-4 w-4" />
              {loading ? "Ukládání..." : "Vytvořit smlouvu"}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateContract;
